---
- name: YUM Install JRE
  ansible.builtin.yum:
    name: java
    state: present
    update_cache: true

- name: Allow 25565/TCP (firewalld)
  ansible.builtin.shell: |
      firewall-cmd --permanent --add-port="{{ server_port }}/tcp"
      firewall-cmd --reload
